- name: "Retrieve master node token"
  ansible.builtin.shell:
    cmd: cat /var/lib/rancher/k3s/server/node-token
  register: master_token
  become: true
  run_once: true
  when: inventory_hostname in groups['masters']
