- name: "Set hostname"
  hostname:
    name: "{{ inventory_hostname }}"
  become: true

- name: "Update apt cache"
  apt:
    update_cache: yes
  become: true

- name: "Install necessary packages"
  apt:
    pkg:
    - net-tools
    - rfkill
  become: true

- name: "Upgrade packages"
  apt:
    upgrade: safe
  become: true

- name: "Remove unnecessary packages"
  apt:
    autoremove: yes
  become: true

- name: "Disable Wifi interface"
  ansible.builtin.command: rfkill block wifi
  become: true

- name: "Disable Bluetooth interface"
  ansible.builtin.command: rfkill block bluetooth
  become: true

- name: Enable container features
  replace:
    path: /boot/firmware/cmdline.txt
    regexp: '^([\w](?!.*\b{{ item }}\b).*)$'
    replace: '\1 {{ item }}'
  with_items:
  - "cgroup_memory=1"
  - "cgroup_enable=memory"
  become: true

- name: "Check if reboot needed"
  stat:
    path: /var/run/reboot-required
  register: reboot

- name: "Reboot"
  reboot:
  when: reboot.stat.exists
  become: true
